#!/usr/bin/env node
import { program } from "commander";
import { backup } from "./commands/backup";
import { info } from "./commands/info";
import { init } from "./commands/init";
import { migration } from "./commands/migration";
import { organization } from "./commands/organization";
import { project } from "./commands/project";
import { regions } from "./commands/regions";
import { remote } from "./commands/remote";
import { remove } from "./commands/remove";
import { reset } from "./commands/reset";
import { restart } from "./commands/restart";
import { restore } from "./commands/restore";
import { start } from "./commands/start";
import { stop } from "./commands/stop";
import { update } from "./commands/update";
import { user } from "./commands/user";

program.version(process.env.npm_package_version || "unknown");
program.addCommand(init);
program.addCommand(start);
program.addCommand(stop);
program.addCommand(restart);
program.addCommand(remove);
program.addCommand(update);
program.addCommand(reset);
program.addCommand(info);
program.addCommand(regions);
program.addCommand(backup);
program.addCommand(restore);
program.addCommand(user);
program.addCommand(remote);
program.addCommand(migration);
program.addCommand(project);
program.addCommand(organization);
program.parse(process.argv);
